language: objective-c
osx_image: xcode10

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage checkout
  - rm -rf Carthage/Checkouts/UICircularProgressRing/Example
  - carthage build --platform iOS --no-use-binaries --cache-builds --verbose

script:
  - xcodebuild -scheme CVSS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3' build test
